### PR TITLE
change file name to application.py

### PR DESCRIPTION
**Pull request by Delali97**
Change only app.py -> application.py

Everywhere "app" appears in any of the  ".py" files change it to **application**

### CODE REVIEW

**Comment by UltiRequiem** [comment]
Hey! That's cool, more semantic & explicit for sure, just got a question, what is that format.zip?

**Comment by Delali97** [comment]
> Hey! That's cool, more semantic & explicit for sure, just got a question, what is that format.zip?

My bad! That's the zip folder I uploaded to Elastic Beanstalk totally forgot to take it out. Was sharing the repo with a friend.

**Comment by UltiRequiem** [comment]
No problem, if you can rebase taking out that zip I will totally merge it.

**Comment by Delali97** [comment]
@UltiRequiem I've taken it out! Thanks :)

**Comment by UltiRequiem** [comment]
Could you rebase the previous commit so that file never appears in the history? 

More info: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

**Comment by UltiRequiem** [comment]
good luck pal

**Pull request closed without merging**
